export const updatedSourceIds = [
  "douban-group",
  "smzdm",
  "linuxdo",
  "newsmth",
  "nodeseek",
  "zhihu-daily",
  "nowcoder",
  "freebuf",
  "hackernews",
  "kaopu",
  "pcbeta-windows11",
  "sputniknewscn",
  "aihot",
] as const
