/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupjavRouteImport } from './routes/supjav'
import { Route as BangRouteImport } from './routes/bang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CColumnRouteImport } from './routes/c.$column'

const SupjavRoute = SupjavRouteImport.update({
  id: '/supjav',
  path: '/supjav',
  getParentRoute: () => rootRouteImport,
} as any)
const BangRoute = BangRouteImport.update({
  id: '/bang',
  path: '/bang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CColumnRoute = CColumnRouteImport.update({
  id: '/c/$column',
  path: '/c/$column',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bang': typeof BangRoute
  '/supjav': typeof SupjavRoute
  '/c/$column': typeof CColumnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bang': typeof BangRoute
  '/supjav': typeof SupjavRoute
  '/c/$column': typeof CColumnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bang': typeof BangRoute
  '/supjav': typeof SupjavRoute
  '/c/$column': typeof CColumnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bang' | '/supjav' | '/c/$column'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bang' | '/supjav' | '/c/$column'
  id: '__root__' | '/' | '/bang' | '/supjav' | '/c/$column'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BangRoute: typeof BangRoute
  SupjavRoute: typeof SupjavRoute
  CColumnRoute: typeof CColumnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supjav': {
      id: '/supjav'
      path: '/supjav'
      fullPath: '/supjav'
      preLoaderRoute: typeof SupjavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang': {
      id: '/bang'
      path: '/bang'
      fullPath: '/bang'
      preLoaderRoute: typeof BangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$column': {
      id: '/c/$column'
      path: '/c/$column'
      fullPath: '/c/$column'
      preLoaderRoute: typeof CColumnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BangRoute: BangRoute,
  SupjavRoute: SupjavRoute,
  CColumnRoute: CColumnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
